name: connect_action

# Trigger the workflow manually
on:
  workflow_dispatch:

jobs:
  build:
    name: build                        # Name of the job
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.12']
    runs-on: ${{ matrix.os }}             # Operating system for the job
    steps:
      - name: Checkout                 # Step to checkout the repository
        uses: actions/checkout@v4

      - name: Set up Python            # Step to set up Python
        uses: actions/setup-python@v4  # Use v4 for compatibility with pyproject.toml
        with:
          python-version: ${{ matrix.python-version }}       # Specify the Python version
          cache: pip  
      
      - name: Setup tmate session (copy paste ssh command to connect_action to runner)   # Step to set up tmate session
        uses: mxschmitt/action-tmate@v3    
